import AuthProvider from "../components/AuthProvider/AuthProvider.jsx";
import "./globals.css";
import Navbar from "../components/Navbar.jsx";
import Footer from "../components/Footer.jsx";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="z-50 sticky top-0">
            <Navbar />
          </div>

          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
